### ISSUE TITLE
Authorization Endpoints Broken

### ISSUE THREAD

**Issue by ccubed** [joshstar/AniList-API-Docs#100]
**Request**
Type: Get
URL: `https://anilist.co/api/auth/access_token`
Params:
- grant_type = client_credentials
- client_id = my client id
- client_secret = my client secret

**Response**
Status: 404 - Not Found
Content: `'{"error":{"status":404,"messages":["API route not found."]}}'`

Oauth also appears to be broken. My website directs them to anilist's oauth flow where it asks them to hit approve or deny, but upon hitting approve your website redirects them to another endpoint on your end which is expecting a parameter that isn't passed.

They get redirected to:
`http://anilist.co/api/auth/authorize?redirect_uri=https%3A%2F%2Fangelbot.vertinext.com%2Foauth%2Foauthcallback%2Fanilist&state=MY_STATE&response_type=code&client_id=MY_CLIENT_ID&grant_type=authorization_code&scope=`

This page simply returns:
`{"status":401,"error":"unauthorized","error_message":"Access token is missing"}`

Instead of being sent back to my side so we can complete the flow and obtain an access token.

**Comment by joshstar** [comment]
I might be wrong but I'm pretty sure its a post request not a get request for /api/auth/access_token?

**Comment by AndyIbanez** [comment]
It looks like last night's update has broken quite a few things.

When using the PIN flow, when you click accept, it tells you that the form will be sent insecurely. It looks like SSL somehow broke here. That message did not show up before.

Following the authentication flow as described in the documentation seems to be broken now too.

```
    error =     {
        error = "invalid_request";
        "error_description" = "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter.";
    };
}
```

**Comment by danejur** [comment]
I've also noticed some errant behavior (or at least different from before).

When using a refresh token to re-authenticate, I am able to successfully get a new access token. However, a new refresh token is also returned, which is a new behavior. Previously, refresh tokens were (effectively) unchanging, and the same one could be used repeatedly for gaining new access tokens. This was extremely useful in testing applications (as temporarily hardcoding a refresh token is an easy and effective way to test a service layer, as no user interaction is required).

Is this an intended change? Either way, would it be possible for similar functionality to be added back to the API? I would definitely like to avoid having to manage refresh tokens when doing simple debugging and testing, if possible.

**Comment by joshstar** [comment]
The new refresh token should be the same as your current one, you should be able to just ignore it.

**Comment by danejur** [comment]
In my testing in Postman, I've observed that executing an auth request with a refresh token will work the first time (using a given refresh token), and fail all times after that, giving the following error.
![image](https://cloud.githubusercontent.com/assets/5756510/17606465/aaeeea28-5fed-11e6-8c85-c44d4fa982d2.png)

**Comment by danejur** [comment]
Also, just to make sure that my request is well-formed, I'm attaching a snip of what I've been sending.

![image](https://cloud.githubusercontent.com/assets/5756510/17606542/018de7b2-5fee-11e6-8f87-b036882115e0.png)

**Comment by AndyIbanez** [comment]
Oh, so the parameters to request the access token have been changed to POST?

**Comment by danejur** [comment]
@AndyIbanez All of my auth methods have been using POST, both before and after the update last night, and I haven't experienced any problems (other than the refresh token one listed above).

I'm not sure what the intended verb is for them, but it seems like POST seems to be working.

**Comment by AndyIbanez** [comment]
Yeah before last night's update, it was a POST request but the parameters were in the URL. Double checking my code (that worked fine until yesterday's update), it looks like that is the case. I will move the parameters to the body later to see how it goes

**Comment by ccubed** [comment]
Sending the data to the auth endpoints as form data instead of url params works. The OAuth flow seems to be working now too. So it appears that the answer is that the auth endpoints switched to post data.

**Comment by joshstar** [comment]
I'll look into getting this fixed, sorry about this all.

**Comment by danejur** [comment]
@joshstar I'm not sure if this is due to changes that you may have pushed out in the past half hour or so, but it looks like the refresh token that gets returned after authenticating with a refresh token is the same as the one used. However, I am still unable to auth more than once (using that same refresh token gives the "refresh token is invalid" error).

Either way, thanks for looking into this.

**Comment by AndyIbanez** [comment]
@joshstar so it's going to go back to passing the parameters in the GET request? Just checking to see if I should change my logic.

**Comment by joshstar** [comment]
Refresh token should be now working again, you may need to re-auth if you've tried to generate another refresh while it was bugged.

@AndyIbanez As far am I'm aware its always been a POST request, unless I'm looking at the wrong thing I can't find any code/docs stating it was a GET request. It might have just been that it accepted url parameters even though it was a POST request, if that was the case add back that functionality.

**Comment by vincent-paing** [comment]
+1, It's returning 400 Bad Request for me saying grant_type parameter is invalid even thought I've added client_credentials

![Postman Log](http://i.imgur.com/bTl7vSl.png)

**Comment by vincent-paing** [comment]
@joshstar 
Currently I can't pass the access token as a Header. But it works when I do pass the access token as url parameter. 

![POSTMAN Log](http://i.imgur.com/3OB9tMw.png)

**Comment by Kazakuri** [comment]
Should be 
```Authorization: Bearer {{accessToken}}```

**Comment by AndyIbanez** [comment]
>@JoshStar said:
 @AndyIbanez As far am I'm aware its always been a POST request, unless I'm looking at the wrong thing I can't find any code/docs stating it was a GET request. It might have just been that it accepted url parameters even though it was a POST request, if that was the case add back that functionality.

It's fine as it is. It's better to make it a POST with URL encoded parameters. If anything, the way it was before was a little odd (making it a POST request, but sending the parameters in the URL).

I was just asking to see if I should consider my change as permanent or temporary.

**Comment by AndyIbanez** [comment]
What's the consensus on the refresh token going to be? Is it going to change every hour or is it going to stay the same permanently?

My tests run fine one hour and then they will break later. It all looks related to token refreshing.

**Comment by danejur** [comment]
@AndyIbanez I just attempted to hit the authorization endpoint with a refresh token that was generated roughly 8 hours ago, and I was able to get a new access token. That, along with what I believe @joshstar was implying, leads me to believe that they are now effectively permanent.

**Comment by ccubed** [comment]
As far as I'm concerned I'm good with this. Post endpoints want form data, the authorization endpoints are working with those changes, not having expires is something I can easily deal with, OAuth is working great now and I've got my service back up and working for the end users. Unless we want to keep this open for extra discussion, I think it's good to close since we know how to fix it.

**Comment by joshstar** [comment]
Regardless of whether is makes more sense or not this way I don't think a 'stable' api should have any kind of breaking changes, especially like this. I'm working on allowing oauth credentials to be sent in url parameters again like before the update, payload will still be accepted also. Should be live later today.

Sorry if I've been a little short tempered, this update did not go any where as smoothly as I'd hoped.

**Comment by joshstar** [comment]
Okay fix is now live. refresh_token won't be returned went it shouldn't be either like before the update.

**Comment by AndyIbanez** [comment]
> @JoshStar said:
> Regardless of whether it makes more sense or not this way I don't think a 'stable' api should have any kind of breaking changes, especially like this.

I don't disagree, but keep in mind that when passing sensitive data in the URL, it can leak in more places than a request body could. Anything that can log visited URLs (this includes some routers) will include the whole URL query, and will include the access token (and refresh token when used) with it. Also think of school/workplace proxies and unsecured Wi-Fi.

So if the credentials can be sent in the URL, I encourage you to push people to stop doing that and use the request body instead.

It's a small risk IMO, but it's a small risk that can be easily avoided.

**Comment by AndyIbanez** [comment]
The access_token endpoint seems to be broken again.

![](https://puu.sh/qPFya/52e8bb76b4.png)
