### ISSUE TITLE
Token Authentication no longer returns "expires" field.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#101]
I noticed that when authenticating, we no longer get a `expires` field.

I heavily relied on it (instead of the amount of seconds left for the token to expire) to easily calculate when I should refresh the token. I'd really appreciate it if it made it back.

**Comment by AndyIbanez** [comment]
I just manually calculated the expiration time of the token, but it wouldn't hurt to have that item back.

**Comment by joshstar** [comment]
Will get this back, sorry didn't notice the package update removed it. I need to write better automated oauth tests so stuff like this doesn't happen again.

**Comment by joshstar** [comment]
Should be back now.
