### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by danejur** [joshstar/AniList-API-Docs#102]
You may already be aware of this, but just to document it here: It appears that search is currently returning an error with the message text of "No Results" for all search queries.

Neeless to say, this is also affecting the site as well.

Edit: Just to clarify, the status code is 200, but an "error" object is being returned.

**Comment by joshstar** [comment]
Working on a fix now

**Comment by joshstar** [comment]
Should be fixed now, we're trying out some new search stuff so results might be a little strange while we iron it out.
