### ISSUE TITLE
Score_Raw now has maximum of 255

### ISSUE THREAD

**Issue by danejur** [joshstar/AniList-API-Docs#104]
After the last server update, it looks like the score_raw field of a list item has a maximum value of 255 instead of 100 (as indicated in the docs). Will 255 be the new maximum, or is this a bug?

In addition, it looks like sending a PUT or POST to update an animelist item causes the supplied value for "score_raw" to be read by the server as simply "score".
i.e. sending a "score_raw" value of 100 will set the "score" to 25.5 (the new max value) while setting the "score_raw" to 255. Likewise, sending a "score" value of 100 will have the same effect (although this is understandable.)

**Comment by kuchienkz** [comment]
Haha so it's not only me :smile: 

Yup, its definitely a bug. Let's wait for them to fix it
