### ISSUE TITLE
Cant make calls to api/anime/

### ISSUE THREAD

**Issue by sachaw** [joshstar/AniList-API-Docs#106]
If someone could please inform me what I'm doing wrong, firstly getting my access_token is not an issue but when I make a GET request to /api/anime{id} with the header of access_token: {access_token} It always results in a 401, I have replicated the same results on 3 different clients, any information would be helpful, thanks.

**Comment by Kazakuri** [comment]
>with the header of access_token: {access_token} 

it should be `Authorization: Bearer {access_token}` if it's included in the header.

**Comment by sachaw** [comment]
Thanks @Kazakuri
