### ISSUE TITLE
Has the "SmallAnime" model been removed?

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#109]
It looks like everything that used to return an `SmallAnime` is now returning a normal `Anime` model.

For example, `/anime/search/{query}` is documented as:

> Returns small anime models.

But it's effectively returning `Anime` models for me.

I need to know to reorganize my wrapper properly.

**Comment by joshstar** [comment]
This is probably a bug, it should be small model

**Comment by AndyIbanez** [comment]
Thanks. Can you also confirm if `user/airing` is supposed to return `Anime` or `SmallAnime` models?

**Comment by joshstar** [comment]
The user lists (that includes user/airing) are small models

**Comment by AndyIbanez** [comment]
Gotcha, thanks. In that case the bug is affecting those as well.

**Comment by AndyIbanez** [comment]
I'd like to confirm if this model is the same as it was originally documented:

```JSON
{
        "id": 1,
        "title_romaji": "Cowboy Bebop",
        "type": "TV",
        "image_url_med": "http://anilist.co/img/dir/anime/med/1.jpg",
        "image_url_sml": "http://anilist.co/img/dir/anime/sml/1.jpg",
        "title_japanese": "カウボーイビバップ",
        "title_english": "Cowboy Bebop",
        "synonyms": [],
        "image_url_lge": "http://anilist.co/img/dir/anime/reg/1.jpg",
        "airing_status": "finished airing",
        "average_score": "86.8",
        "total_episodes": 26,
        "adult": false,
        "popularity": 7574,
        "relation_type": null,
        "role": null
}
```

Once it gets fixed.

**Comment by joshstar** [comment]
I've updated the anime/manga (series) docs with a table, looks a rather bad on the current theme but on the far right theres mention of whether the value is available in the small model.

**Comment by AndyIbanez** [comment]
Wow, this is perfect. Thanks.

This puts it much better into perspective how the models are, and by marking the property types and whether they can be null will really save a ton of guesswork.

Just the heads up, the "airing" field that returns in `user/airing` doesn't seem to be documented anywhere or in the toDo's.

Other than that thanks a lot for this. It's bummer I will have to rethink how some things are organized on my end, but having that as a reference is going to help a lot.

**Comment by joshstar** [comment]
Will work on the docs a bit more over the next couple weeks, will close this for now.
