### ISSUE TITLE
/user/{ID or Username}/animelist/ should return only a dictionary of lists.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#113]
Not a big deal but a bit weird regardless. Making a call to this will essentially give you a User Model with an extra property for your lists. It should just return a dictionary of "Record" arrays.

**Comment by joshstar** [comment]
Yeah I'm not really a fan of how we do this either, it makes good code separation a bit more difficult on the back end too. For APIv2 you will just get list entries, and then if you want to the user data to you'll either already have it cached, can make another request, or can 'combine' the user request with the list request. 

I'll close this as its something I've always planned to do v2 but just never mentioned it.
