### ISSUE TITLE
api/user/{id or username}/animelist/raw should return more information for each Record.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#114]
A record looks like this when append "raw" to an anime list:

```JSON
      "record_id": 2926512,
      "series_id": 6682,
      "list_status": "completed",
      "score": 2,
      "score_raw": 20,
      "episodes_watched": 12,
      "chapters_read": 12,
      "volumes_read": 0,
      "rewatched": 0,
      "reread": 0,
      "priority": 0,
      "private": 0,
      "hidden_default": 0,
      "notes": "",
      "advanced_rating_scores": [],
      "custom_lists": [],
      "started_on": null,
      "finished_on": null,
      "added_time": "2014-04-10T07:39:21+09:00",
      "updated_time": "2014-11-28T02:12:00+09:00"
```

Having this call is a good idea to return less data and save bandwidths, but as it currently is, I don't know what I could use this record for. It has the series ID, but nothing else to inspect it on the first call. It should return with an extra property (or three) for the anime title to make it inspectable on the first look.

I'd also like to piggyback on my issue #113 for this as well, as it returns the whole user information.

**Comment by joshstar** [comment]
The raw route is primarily intended just for backup use, but we still haven't gotten around to doing an AniList import for it. Adding the series model with just a few values would be a bit of a pain to do with how we handle models, and I don't really think the bandwidth saved by missing out on the details is really worth it so I probably won't make any changes here.
