### ISSUE TITLE
Open a "user/animelist" call.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#115]
It's a bit weird that we can get the list for any username but we can't get the list of the currently authenticated user directly.

Worst case scenario, we have to query /user before querying animelist to get the current user's list. This is currently not a big deal I think, but the API should require less calls, specially if rate limiting becomes a necessity in the future.

(And with that, I apologize for opening 3 issues in one go!)

**Comment by joshstar** [comment]
This is a good suggestion, will look into getting it done soon.

**Comment by joshstar** [comment]
Sorry this never happened, as APIv2 is coming up I'll be closing this.
