### ISSUE TITLE
Updating animelist with started_on and finished_on

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#116]
The documentation does not reflect the POST or PUT changes to update records on our lists to add the dates.

I have tried the following fields with no luck:

`start_date`
`end_date`
`started_on`
`finished_on`

With data like 2016/08/08/ but my record still does not have start and finished dates.

EDIT: Also there doesn't seem to be a way to to change the `private` property in the post body.

**Comment by joshstar** [comment]
started_on and finished_on should work with any dates like 2016/08/08 (YYYY/MM/DD), they work on the anilist site so they should work on the api (its the same thing). private is 0 or 1. Again you might be better off checking if/how its done on the anilist site by checking the network requests in the dev tools as it uses the exact same api for the most part.

**Comment by AndyIbanez** [comment]
I ultimately got it work with start_date and end_date. It kept failing because my MM and DDs didn's have leading zeroes.
