### ISSUE TITLE
Getting 500 when trying to update an animelist entry

### ISSUE THREAD

**Issue by asermax** [joshstar/AniList-API-Docs#120]
We've been using anilist's API from [tsuiseki.moe](https://tsuiseki.moe) for a good while now, but I've noticed that lately (I don't know exactly since when, probably a couple of months now) we're getting a 500 error every time we try to update an `animelist` entry.
I was wondering if there was any change on the API that we should be aware of or if there's any way for us to debug this issue. We haven't touched the portion of the code that makes the calls to the API, so I'm a bit rusty on how it works, but I can try to play around with it if you need some other info on the issue (the request headers, payload, etc).

Thanks!

**Comment by Kazakuri** [comment]
The only thing that I know of changing was the addition of `score_raw` as an option to the `animelist` endpoint, but that was well over a year ago.

If you provide me with a sample call you're making I can try to look into it.

For example: 
```
POST https://anilist.co/api/animelist?id=20758&episodes_watched=7
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type: application/json
```

**Comment by asermax** [comment]
After some debugging I found out that what was actually failing was the auth token refresh. After throwing away my old credentials and authenticating again, everything seems to be working fine, so I assume it was related to the buggy refresh token mentioned in #100.

I'm not sure how to reproduce it, but I think it's worth taking a look into why the API is throwing a 500 instead of a 401 or a 400. 

Anyways, my issue seems to be solved, so I'll close this one.
Thanks for the response and sorry for the noise!
