### ISSUE TITLE
Score Raw does not set right score.

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#122]
@joshstar I just fixed a few score issues in the app and I stumbled upon this issue: 

Pushing a score_raw of 50 should be 5.0 but if I check it on AL it is set on 25.5. (Makes no sense XD)
Pushing a score_raw of 5 should be 0.5 but if I check it on AL it is set on 5.0.

Did the score_raw got mixed up with score?

**Comment by joshstar** [comment]
Sorry I haven't replied to this yet, I've been super busy with uni starting again. I'll try getting this fixed within the next week or so.

**Comment by danejur** [comment]
Excellent! Looking forward to this getting fixed.

**Comment by jonathanslalom** [comment]
Hey @joshstar , any update on if/when this issue will get fixed? I've noticed the pattern mentioned above by @ratan12 when the user has a scoring method of "10.0", but it looks like when they use smiley faces or stars, pushing a raw score (even one that has a corresponding "typed score", such as :| ) causes the actual score to be set as 0.

This is probably the biggest showstopper for app development for me (at least for the current feature additions), so I would greatly appreciate it if you could take a look. Thanks again!

**Comment by joshstar** [comment]
Oh shit, really sorry about this. Just pushed a fix now.

**Comment by joshstar** [comment]
I'll close this now as I'm pretty sure its fix, but please do send me a message if its still an issue.
