### ISSUE TITLE
Modify an anime's progress "silently"

### ISSUE THREAD

**Issue by kuchienkz** [joshstar/AniList-API-Docs#126]
Is there a way to modify an anime's progress "silently"? 
"silently" means, no feed will be made.

**Comment by joshstar** [comment]
At the moment the only way to do it is to set the anime/manga list entry to private. This is a newer thing so I don't think I've actually documented yet, the key is 'private' and its a numeric boolean so 0 is false and 1 is true.

**Comment by kuchienkz** [comment]
Whoa that's better! Thanks!
