### ISSUE TITLE
Open sourcing anilist

### ISSUE THREAD

**Issue by mrahhal** [joshstar/AniList-API-Docs#131]
I tried asking in one of my old threads on anilist but it's hard to reach to other people there, so I'm going to ask here.

As it turns out, the last update on this is 5 months ago. I know that Uni is still a priority so won’t pester you much, but any update? A hint would be nice, are you on schedule or will there be delays?

**Comment by joshstar** [comment]
Probably not until after APIv2 is out and stable, as I want to make sure everything has tests and documentation, a lot of stuff does at the moment but theres a fair amount of older code without them. As I'm basically rewriting everything for v2 currently I figure I may as well not bother going back to the older code and improve tests and add docs when its going to be removed soon.

**Comment by mrahhal** [comment]
I've been following #63 and there's a lot of good ideas (as well as issues), so is the progress on V2 good or are you being delayed because of problems?

One more thing, it makes sense to have a comfortable base before opening it up but I don't feel like having everything perfect or even complete (especially docs and api for example) beforehand is worth it. That's the point of open source. When anilist gets open sourced I believe the community will be a major help in patching those up, and maybe also driving how the api should look like and reporting the issues early on (it's the foundation of the site after all).

**Comment by joshstar** [comment]
Progress with v2 is good but just a little slow with Christmas and now exams but should be getting into it full swing again in a couple weeks. 

I plan on having quite a few pre-releases of v2 before its stable release so we can get feedback on it before anything is concrete. 

Yeah I know what you mean but I would really rather the community work on new things that they find interesting and less so adding tests and docs, I know its something that will happen as well but if anyone wants to change code that doesn't have tests then its going to be really hard to manage those prs, and those changes will be pretty redundant with v2 replacing it all a couple months after.

**Comment by mrahhal** [comment]
I totally understand. Great work on anilist 👍
(It'd be super cool if you can maybe create a thread on anilist and keep us developers updated on the state of things from time to time so that nobody has to explicitly ask the questions)
