### ISSUE TITLE
Possible adjustment to activity_history in user models

### ISSUE THREAD

**Issue by theIglooo** [joshstar/AniList-API-Docs#134]
Currently it's an object with new members appearing for every new day that you watch or read something, this seems like it would make more sense to be an array of objects like this:
```json
"activity_history": [
  {
    "date": "2016-07-25",
    "count": 8,
    "color": "#1e6823"
  },
  {
    "date": "2016-07-27",
    "count": 1,
    "color": "#d6e685"
   }
]
```

**Comment by joshstar** [comment]
Activity history isn't really api stable (if something isn't documented its probably not api stable) its just available as the AniList front end uses the same api as the public api. I need to make some changes to it anyway so I'll look into this as I can understand it being a pain in strictly type languages but at the moment having it as an associative array makes it a ton easier to work with on the AniList front end.

**Comment by theIglooo** [comment]
I figured out the problem I was having earlier with the current structure, just a bit of a brain fart at midnight. If it's easier and more efficient to keep it as-is then by all means do so and close this issue.
