### ISSUE TITLE
404: api route not found on OAuth Pin authentication request

### ISSUE THREAD

**Issue by mrspits4ever** [joshstar/AniList-API-Docs#136]
Hello there, i've been working on a C# wrapper for AniList for a while and came around to implementing the pin-based authentication for the client. Now when i tried to open the following request I got a **404: api route not found** error and i'm currently scratching my head as to why that is.
this is the url that I open in the browser:
https://anilist.co/api/auth/access_token?grant_type=authorization_pin&client_id=mrspits4ever-x83td&response_type=pin

any ideas?

**Comment by Kazakuri** [comment]
```
POST: auth/access_token

Url Parms:
grant_type    : "authorization_pin"
client_id     :  Client id
client_secret :  Client secret
code          :  Authorization pin
```

It's a POST request, you can't view it by opening it in the browser.

Though looking at your params you're probably intending to do

```
GET: auth/authorize

Url Parms:
grant_type    : "authorization_pin"
client_id     :  Client id
response_type : "pin"
```

Which is `authorize` instead of `access_token`
