### ISSUE TITLE
Option to search with genres?

### ISSUE THREAD

**Issue by MeLikeChoco** [joshstar/AniList-API-Docs#137]
The api is a little confusing to me, is there a way to search with multiple genres as "tags"

I see on the documentation that "Genres" are TODO. Has it been implmented yet?

**Comment by Kazakuri** [comment]
The `ToDo` is just for documentation of genres within a series, you can indeed filter by genre.

With the [browse endpoint](http://anilist-api.readthedocs.io/en/latest/series.html#browse) you can use the `genre` parameter to list series with all of the genres provided.

**Comment by MeLikeChoco** [comment]
I just face palmed

**Comment by MeLikeChoco** [comment]
Is there a random search in the works?

**Comment by Kazakuri** [comment]
Not as far as I know, there wouldn't really be a place for it on the site. Maybe you can convince Josh to add something like that for APIv2
