### ISSUE TITLE
"redirect_uri" changes to "Array"

### ISSUE THREAD

**Issue by paz3lik** [joshstar/AniList-API-Docs#138]

**Comment by Kazakuri** [comment]
Probably going to need a bit more information than that, `auth/authorize` still seems to be working fine for me.

1. Are you trying to use `authorization_code` or `authorization_pin`?
2. Does your `response_type` match your `grant_type`?
3. Is your `client_id` valid?
4. If you're using `authorization_code`, do you have a valid `redirect_uri` that you're supplying?

**Comment by paz3lik** [comment]
Oh, "redirect_uri" really had a wrong value. That is my mistake. Partially.
If don't change the any value on settings page, and then click [Save], the "redirect_uri" changes to "Array".
