### ISSUE TITLE
Problems with auth/access_token

### ISSUE THREAD

**Issue by danejur** [joshstar/AniList-API-Docs#139]
When attempting to submit a POST request to auth/access_token, I am getting a 404 response. The fully qualified URI I am using is:
`http://anilist.co/api/auth/access_token`

Needless to say, this is fairly critical, as it stops users from being able to authenticate in any way, thus rendering the rest of the API useless.

**Comment by Kazakuri** [comment]
Use HTTPS to access the API instead of HTTP.

**Comment by danejur** [comment]
Yup, was actually just about to update this. Sorry about that. Was non-SSL access revoked recently? It was working up until a few days ago.

Either way, good deal. Thanks, @Kazakuri.

**Comment by Kazakuri** [comment]
I don't think anything has changed on the API in quite some time unless it was changed in a server config, which is very unlikely.

As far as I know a bunch of routes do work over HTTP, but access tokens really shouldn't be transported over HTTP anyways.

**Comment by danejur** [comment]
> As far as I know a bunch of routes do work over HTTP, but access tokens really shouldn't be transported over HTTP anyways.

True that. Alas, lesson learned.
