### ISSUE TITLE
404 - Page not found-Chan =(

### ISSUE THREAD

**Issue by MauricioRibeiroA** [joshstar/AniList-API-Docs#140]
Hi everybody,

I'm starting to study the HTTPS requests so I'm having a hard time to understand everything about the authentication methods. I tried to get the token with the method:
https://anilist.co/api/auth/authorize?grant_type=authorization_code&client_id=mau***&redirect_uri=Array&response_type=code and I got the 404. 

Thanks!

**Comment by Kazakuri** [comment]
It shouldn't be 404ing at all, the link you posted 401s for me.

`GET auth/authorize` returns 401 if the `client_id` or the `redirect_uri` aren't correct, make sure they match with what you have on the developer page.

**Comment by MauricioRibeiroA** [comment]
Thats because I used the stars on my client_id when I posted here. 
When I fill in with the right one I get the 404. =(
![ps anilist](https://cloud.githubusercontent.com/assets/21245849/23485753/97075b90-febb-11e6-9fed-26912aca9c76.png)

**Comment by Kazakuri** [comment]
You don't need to censor your client_id, only the client_secret.

If I test with a client_id of mine it 401s with the wrong redirect_uri
https://anilist.co/api/auth/authorize?grant_type=authorization_code&client_id=kazakuri-vs1xk&response_type=code&redirect_uri=something
and works fine with the correct redirect_uri
https://anilist.co/api/auth/authorize?grant_type=authorization_code&client_id=kazakuri-vs1xk&response_type=code&redirect_uri=Array

It's a bit weird since usually a [bad API route 404](https://anilist.co/api/auhth/authorize) is still a JSON response... Can you post the exact url that redirects you to the 404 page?

**Comment by MauricioRibeiroA** [comment]
You're right. I tried the same request with my infos now and got the client authentication failed. 
https://anilist.co/api/auth/authorize?grant_type=authorization_code&client_id=mauribeiro-ps8tt&response_type=code&redirect_uri=http://localhost:8080

**Comment by Kazakuri** [comment]
Looks like the redirect_uri didn't update on the developer page.

https://anilist.co/api/auth/authorize?grant_type=authorization_code&client_id=mauribeiro-ps8tt&response_type=code&redirect_uri=Array

It works for me with the redirect_uri as Array

**Comment by MauricioRibeiroA** [comment]
I tried before with the Array, but when I do this I get the 404 =P
Do I need to change my redirect_uri?

**Comment by Kazakuri** [comment]
Yeah, changing the redirect_uri on the developer page to `http://localhost:8080` and clicking save should make it work.

**Comment by MauricioRibeiroA** [comment]
When I use the Array I can have access to the first screen and then break to 404, but when I use 8080 it breaks by the authorization problem. 
I'm trying in another way with the Sinatra a RubyGem and I could receive the code on my terminal (with another localhost). Now i'm trying to figure out how to ask for the lists. Lol!
Keep helping me my friend =)

**Comment by MauricioRibeiroA** [comment]
Kon'nichiwa @Kazakuri ! in this GET "user/{id || displayname}/animelist" at the user I should put my client_id or the same name that I have at the anilist website? The code after the "user" I know how to read, I'm just starting understand the HTTPS verbs.

**Comment by MauricioRibeiroA** [comment]
Kon'nichiwa @Kazakuri I got it! I took the whole day studying restfull apis and https verbs to understand the sintax. Thks for your time!
