### ISSUE TITLE
Error 400 (SQL) POST/PUT requests 

### ISSUE THREAD

**Issue by LostArchives** [joshstar/AniList-API-Docs#141]
Hello everyone,

I'm developing a wordpress plugin with AniList API :+1:  but I have a problem with POST and PUT requests. (error 400 : "SQL ERROR")
I tried my queries with my own functions and with hurl.it and I have the same SQL error.

For example, this is the query for the user activity
https://ibb.co/gg20gF
And this is the response
https://ibb.co/h7SBov

I have no problem with other requests (DELETE,GET) and the POST request to refresh the token works too so I suppose the problem comes from my values or perhaps there's a missing parameter in my headers except the Content-Type which is already present.

**Comment by LostArchives** [comment]
Solved.
The problem was that the access token must be in headers ( Authorization => Bearer my_access_token) and not in body (access_token => my_access_token is not correct for POST/PUT requests).
The body is only reserved for the payload.

**Comment by joshstar** [comment]
Hmm I'm pretty sure I made it disregard any access_token in the payload. I'll try get this fixed as I'm sure others will have similar issues.
