### ISSUE TITLE
Error 301 Moved Permanently

### ISSUE THREAD

**Issue by T4RI0** [joshstar/AniList-API-Docs#142]
First off all, im kinda new to https GET,POST and so there can be alot of mistakes. So my problem is if I send a GET Request as seen below I receive an Error 301, I tried many diffrent ways, but I think my mistake should be in the GET Request since Im not to sure how its supposed to look like and I didnt really found any examples.  If it matters im using C# for this programm and here is the stuff I use cut down to the most important ones. 
Im using Sockets for the sending and receiving of the data.
Im using Port 80,I know that it is the HTTP Port not the HTTPS Port(443) but I got another Error with the HTTPS Port. 
The IPAddress I use is 137.74.221.138(from  https://anilist.co/api/).
Here is the full GET request im sending to the Server: "GET https://anilist.co/api/auth/authorize?grant_type=authorization_code&client_id=t4ri0-hy07z&redirect_uri=https://anilist.co&response_type=code"

Alot of the stuff im using I found in other posts so it might not work for the stuff im using. I hope someone can help me.

**Comment by Kazakuri** [comment]
If you're new to it, you probably shouldn't be using sockets for web requests, I'd recommend [HttpWebRequest](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest(v=vs.113).aspx).

The url that you're requesting isn't really meant for a program to automatically handle. It requires the user to login and manually allow the program to access AniList on their behalf. Typically that means opening the url in a WebView or in the user's default browser and then setting up a uri scheme or getting the user to copy and paste the code back into your application.

**Comment by danejur** [comment]
First off, I'd recommend trying out one of the many REST libraries available for .Net (assuming you are using C# .Net). although there are a few for .Net Core as well. A favorite of mine is [RestSharp](http://restsharp.org/), but others are good as well. This saves you from having to construct a WebRequest, deal with Streams, etc.

Also, as @Kazakuri mentioned, the URL you supplied returns a an actual page that will allow the user to approve client access, and then redirect to the given "redirect_uri" with the token required for access. For instance, after clicking "Approve" on the page that is returned, I am redirected to the following URL: https://anilist.co/?code=[token_goes_here]. This should be displayed in a WebView, or something similar (once again, as @Kazakuri previously stated).

I have a pretty decent amount of experience working with this API (and web API's in general) using C#, so please feel free to email me if you have any questions or need some help!

**Comment by T4RI0** [comment]
Thanks for your help and will try your recommedations. Since the GET request is wrong could you give me an example of a working GET request since I still dont know how its supposed to look like. Thanks in advance and I will email you @danejur if Im going to need any major help :)
