### ISSUE TITLE
Access Token path for 'client_credentials' does not exist

### ISSUE THREAD

**Issue by toashel** [joshstar/AniList-API-Docs#143]
Hi, I was using the AniList API for a hobby project a month or two ago, and utilized the client_credentials access token grant to handle GET data. After checking on my project again, it seemed that the wrapper API was not functioning properly and after going into Postman I was getting the following error message when trying to get an access token.

`{
  "error": {
    "status": 404,
    "messages": [
      "API route not found."
    ]
  }
}`

Is there something I am forgetting here, as I have tried different client_id/client_secret apps and the other type of grants seem to work fine. Thanks in advance!

**Comment by Kazakuri** [comment]
Without more information my guess is that you're not using HTTPS for the POST request.

Please note that the official API url is `https://anilist.co/api/` and HTTPS is required.

**Comment by toashel** [comment]
Oh man that's embarrassing, you were totally right - seems to work fine now. Thanks!

**Comment by Kazakuri** [comment]
We've had a couple issues about that now, the error message should really be a bit more clear.
