### ISSUE TITLE
URL of authorization form and scopes

### ISSUE THREAD

**Issue by PedBerTor** [joshstar/AniList-API-Docs#144]
Hi everyone. I need the authorization form url to complete the OAuth configuration. Also, i dont know where i have to specify grant_type field because im using scopes. The following photo represent how im doing the configuration:

![captura](https://cloud.githubusercontent.com/assets/16528784/25501595/98634166-2b93-11e7-8c51-d2f8f4c30833.JPG)

**Comment by Kazakuri** [comment]
Assuming you're using the [Google API Client Library for Java](https://developers.google.com/api-client-library/java/google-api-java-client/oauth2), my best guess would be that the `authorizationFormUrl` should be the route for `auth/authorize`.

From the sound of it on their documentation, the scopes seem to be a list of supported permissions you want, but AniList doesn't do anything like that. So I'd imagine that you'd just stick the `grant_type` and `response_type` fields in the URLs as URL params.

**Comment by PedBerTor** [comment]
Ok, thanks.
