### ISSUE TITLE
TV anime search by title - URI example?

### ISSUE THREAD

**Issue by PedBerTor** [joshstar/AniList-API-Docs#145]
Hi everyone. As i can see in the api documentation, i can search animes by title using this url:

https://anilist.co/api/{series_type}/search/{query}

Can you give me an example with series_type and query? Thanks.

**Comment by Kazakuri** [comment]
`https://anilist.co/api/anime/search/lucky%20star`

**Comment by PedBerTor** [comment]
Thanks.
