### ISSUE TITLE
Access token is missing

### ISSUE THREAD

**Issue by PedBerTor** [joshstar/AniList-API-Docs#146]
Hi! I'm trying to get the json response for anime search but i always get an error: "access token is missing". What is the uri to get the token and how is the format? thanks

**Comment by Kazakuri** [comment]
The access token is provided by you either using the header:
`Authorization: Bearer <access token>`
or the url param:
`?access_token=<access token>`

To get the access token you need to authenticate using your client as described [here](http://anilist-api.readthedocs.io/en/latest/authentication.html).

The simplest method is a client credentials grant, which doesn't require the user to login so you can't access a user's resources, but you can still do things like search anime and read the forum.

As described [here](http://anilist-api.readthedocs.io/en/latest/authentication.html#grant-client-credentials), you POST to `auth/access_token` and the access_token is the `access_token` field in the JSON response. You'll have to renew that token after an hour when it expires by repeating the POST.

**Comment by PedBerTor** [comment]
@kazakuri ok so I have to do post to https://anilist.co/apiauth/access_token


—
You are receiving

**Comment by PedBerTor** [comment]
Sorry my smartphone got crazy. @kazakuri I said that I have to do post to https://anilist.co/apiauth/access_token ? If it correct where I specify the grant type?

—
You are receivin

**Comment by Kazakuri** [comment]
The url is `https://anilist.co/api/auth/access_token`.

The documentation says:
```
POST: auth/access_token

Url Parms:
grant_type    : "client_credentials"
client_id     :  Client id
client_secret :  Client secret
```

So you POST to something like `https://anilist.co/api/auth/access_token?grant_type=client_credentials&client_id=<your client id>&client_secret=<your client secret>`

**Comment by PedBerTor** [comment]
Ok thank you very much. Know I can continue with development.

**Comment by PedBerTor** [comment]
@Kazakuri I trying to request the access token with the url that you said:

https://anilist.co/api/auth/access_token?grant_type=client_credentials&client_id=pe****&client_secret=hx****

But i got 404 error:

**{"error":{"status":404,"messages":["API route not found."]}}**

**Comment by Kazakuri** [comment]
If that error shows up that means you're performing a GET request instead of a POST request.

**Comment by PedBerTor** [comment]
@Kazakuri ok i got it. Thx
