### ISSUE TITLE
Unrecognized field "access_token"

### ISSUE THREAD

**Issue by PedBerTor** [joshstar/AniList-API-Docs#147]
Hi! I have a problem when i try to map the access token into java class. I used json2pojo to obtain a java class called "AnilistToken.java" with all response attributes:

![anilisttoken](https://cloud.githubusercontent.com/assets/16528784/25564739/ff6501e2-2db9-11e7-933a-10d2e90d619e.JPG)

I have a class called "AnilistTokenResource.java" that i use to do post to the server using the get token uri (with client id, grant type and client secret).

![anilisttokenresource](https://cloud.githubusercontent.com/assets/16528784/25564757/4fe6830c-2dba-11e7-8b20-03dba9b9a3da.JPG)

The problem is that when i use "AnilistTokenResource.java" to do post, i receive a 422 error (Unprocessable Entity):

![error](https://cloud.githubusercontent.com/assets/16528784/25564772/8dbf0c08-2dba-11e7-8bd2-1675336cc5f0.JPG)

As you can see the error is cause by: 

**com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException:Unrecognized field "access_token" (class aiss.model.anilisttoken.AnilistToken), not marked as ignorable (5 known properties: "tokenType", "expires", "accessToken", "expiresIn", "additionalProperties"])**

I do not know why i have this error beacuse the response is json format, and i use that format for all apis in my project, using the same request/mapping system. 

Do you have any solution? I hope you can help me. Thanks

**Comment by PedBerTor** [comment]
I've just added @JsonIgnoreProperties(ignoreUnknown=true) in the token class but i supposed now the token "access_token" field is null and i cant request the anime data:

![captura](https://cloud.githubusercontent.com/assets/16528784/25565441/cf6a87fc-2dc6-11e7-94de-cc639f175586.JPG)

Is there any way to get "access_token" field of the token?

**Comment by Kazakuri** [comment]
It might be worth stepping through the code with a debugger to see what the Restlet library is doing / looking for specifically, but if I was to hazard a guess I would try switching your POJO properties from camel case names to snake case (e.g. `accessToken` to `access_token`) since the json2pojo might have done the conversion but the Restlet converter library might not do it.
