### ISSUE TITLE
Refresh Token expiring?

### ISSUE THREAD

**Issue by danejur** [joshstar/AniList-API-Docs#148]
Over the past week or two, I've noticed that attempting to re-authenticate with the api using a refresh token (and a properly formed request) returns a 500 with the error text of "Bad Request".

If I go through the standard authorization workflow and re-authorize whatever account I am using at the time with the api key I have assigned, I am able to re-authenticate using the new refresh token.

Is it possible that refresh tokens are getting blacklisted, or is there now a hard limit to how long they last? Naturally, this is somewhat frustrating, as the user must re-authorize the app against AniList if they wish to continue use.

Any thoughts here?

**Comment by Kazakuri** [comment]
Just to make sure, you're getting a 400 error, not a 500 error, right?

As far as I know (and as far as my understanding of Josh's code shows) refresh tokens do have a TTL and get rotated after a week so the very next request after a week will expire that token and generate a new one that is returned alongside the access token.

For example:
```
POST: auth/access_token

Url Parms:
grant_type    : "refresh_token"
client_id     :  Client id
client_secret :  Client secret
refresh_token :  Refresh Token
```

could return:

```
{
    access_token: "n6c4Rk1lnTD3CY1lKfJVlRXvIGOH4yLhAVyf5Iz"
    token_type: "bearer"
    expires: 1414233512
    expires_in: 3600
    refresh_token: "X2Bxj1KzjsoaD4FCj6A0MGFWdYlGgoc31L70eSAQ"
}
```

This should really be documented if it is indeed the case.

**Comment by danejur** [comment]
The status code is indeed 500, which made me balk when I first noticed it.

I guess the refresh token expiration is new, then. I have been using the same tokens for what seem to be months on end without any problem. But if it really is a matter of expiration and the new one being returned with the last request, that isn't a problem. Easy to work around. Can we get confirmation from @joshstar on this?

**Comment by joshstar** [comment]
Sorry about that, should be fixed on our end now

**Comment by danejur** [comment]
Cool, thanks Josh.

**Comment by danejur** [comment]
Just as a follow-up, @joshstar:

Would it be possible to have that response return a 400 or a 401? That is, if the user hits the auth/access_token endpoint with an invalid refresh_token. Right now, its returning a 500 (as mentioned above), but I get the feeling that this isn't really a case of a "server error". Some (shitty) REST clients don't handle 500s the same way they deal with all other status codes, so this would be very helpful.
