### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by xtremado** [joshstar/AniList-API-Docs#149]
hi, I try to create review but I can't because it show this [image](https://gyazo.com/7e57c317402280e8b74fb626275b6e35) I try to refresh token but I can't use it with this .
Show how I can use token in  [get anime search](https://gyazo.com/31277a79349ffcb43833c5dddea4c59b).
what's the problem?

**Comment by Kazakuri** [comment]
As noted in the [documentation for authentication](http://anilist-api.readthedocs.io/en/latest/authentication.html)

```
Now to access the resource server on the resource owner’s behalf, simply include the following header with all your requests

Authorization: Bearer access_token
```

Since creating a review is something that can only be done by a resource owner token (vs client credentials), you need to include it in the Authorization header.

**Comment by xtremado** [comment]
thanks other question how i get redirect uri for authorization_code? I'm searching but i don't found

**Comment by Kazakuri** [comment]
It'll be the `Client Redirect Uri` you entered on your client page on the [developer settings page](https://anilist.co/settings/developer).

**Comment by xtremado** [comment]
I'm trying without a client redirect uri only put clientredirect uri and i get the code but if i use the code i have this problem 
![b945fb36e3f31761427e6f8240f3f856](https://cloud.githubusercontent.com/assets/27725192/26018236/e0ccd274-376d-11e7-8878-60a06efacb0b.png)

**Comment by Kazakuri** [comment]
You're missing the `=` after `redirect_uri`, but in either case, you don't need to provide the `redirect_uri` for that route, only the one to get the code.

**Comment by xtremado** [comment]
what is the error in "code"? i cant get the token for post,put and delete

**Comment by Kazakuri** [comment]
![http://i.imgur.com/tcIjKUS.png](http://i.imgur.com/tcIjKUS.png)

You're not supplying the code param because `&redirect_uri` isn't a valid url param, either add an `=` to the end of it or remove it since it's not required anyways.

**Comment by xtremado** [comment]
[with &redirect_uri=](https://gyazo.com/b7377134f55b9fecffff53b75a095772)
[without &redirect_uri](https://gyazo.com/d8b0b177f4bf1537b366d8950b3bddb3)
i don't know why i can't get this .

**Comment by Kazakuri** [comment]
Oh woops, I misread the documentation, `redirect_uri` is required when getting it from the auth code, but not from the refresh token. My mistake.

As far as I know, you should only be getting that 404 error if you're using the wrong HTTP method, did you use a POST request for the "with &redirect_uri=" request?

**Comment by xtremado** [comment]
i'm trying with pin but it show this
![084eb1903d3bb9d4b92d1cdaaacbc2d4](https://cloud.githubusercontent.com/assets/27725192/26018957/74141a52-3772-11e7-8b68-d2d3359bd945.png) and its the same pin that give me [pin](https://gyazo.com/050da5ebb0286db8279e38bdeccdb450
)

**Comment by xtremado** [comment]
plis i need help with error invalid request
![bdbb63f78375de0215f1af4eb08b5518](https://cloud.githubusercontent.com/assets/27725192/26027345/d9cc2502-380c-11e7-929a-e250d9b14bb7.png)

**Comment by Kazakuri** [comment]
I honestly can't see anything wrong with either of those requests.

I've been playing with it myself and provided that the code is valid I've been able to authenticate properly.
If I use a code that has already been used I do receive that error, which is to be expected.

For example: 
Valid:
![http://i.imgur.com/Kyzd3JU.png](http://i.imgur.com/Kyzd3JU.png)

Already used:
![http://i.imgur.com/gMFmIFf.png](http://i.imgur.com/gMFmIFf.png)

**Comment by xtremado** [comment]
finally i get i refresh pin
![18dc72b9970b594fda8145369dab8082](https://cloud.githubusercontent.com/assets/27725192/26103105/4287e9be-3a38-11e7-8d9a-e187d4fec057.png)
and i can use refresh token
[image](https://gyazo.com/374aa38972ecf5a0a9ac3344f5476fa9)
but when use for review for example show this
[image](https://gyazo.com/bc5d585d5b0ed989fa0d35419d23c5a4)
whats the problem? i have a token that i receive with authorization pin grant type.

**Comment by Kazakuri** [comment]
Like I said in my first reply, you need to supply it in the `Authorization` header with the value `Bearer access_token`

**Comment by xtremado** [comment]
could you give me a example? I'm trying but i can't do

**Comment by Kazakuri** [comment]
![http://i.imgur.com/Dhj0CwA.png](http://i.imgur.com/Dhj0CwA.png)

**Comment by xtremado** [comment]
[thanks a lot](https://gyazo.com/abab60f9d71f7ddf858c33cbe0bb9a8e)

**Comment by xtremado** [comment]
I'm trying to use in a user list post,put and delete but i don´t know how do it i know in postman but i try to do in my mashup could you show me how to do? the same for token i can in postman but i don´t know how to get it in my mashup 
![imagen](https://cloud.githubusercontent.com/assets/27725192/26167149/448c8f0e-3b36-11e7-9710-47ab333d1eee.png)
![imagen](https://cloud.githubusercontent.com/assets/27725192/26167183/637315c8-3b36-11e7-8ce9-f5cdba726341.png)
I'm trying to do this in my mashup

**Comment by Kazakuri** [comment]
You only need to supply the parameters you want to change from the payload section

![http://i.imgur.com/iqUg5SS.png](http://i.imgur.com/iqUg5SS.png)

![http://i.imgur.com/7hF2uuC.png](http://i.imgur.com/7hF2uuC.png)
