### ISSUE TITLE
Way to get list of users watching/completed/ptw an anime?

### ISSUE THREAD

**Issue by Goldensunboy** [joshstar/AniList-API-Docs#150]
The anime model has stats concerning how many users are watching, plan to watch, completed, dropped (etc.) a show, but is there a way other than hoarding (which is against ToS) to see which users these are?

**Comment by Kazakuri** [comment]
Not quite at the moment, the series activity feed (`https://anilist.co/api/anime/:id/activity`) has 12 entries per page of which users did what to a series.
Other than that, the series following feed (`https://anilist.co/api/animelist/:id/following`) gives a bit more direct information, but only about users you're following.

By the sounds of it, this seems like something that can be achieved with GraphQL and APIv2 though. Josh has been working hard on it recently so there shouldn't be too long of a wait for it.

**Comment by joshstar** [comment]
Yeah not something we provide at the moment but will be possible in APIv2:
![Apiv2](https://puu.sh/wl2o0/71025c74dc.png)
