### ISSUE TITLE
Issues trying to access Characters/Staff API

### ISSUE THREAD

**Issue by yydrvs** [joshstar/AniList-API-Docs#151]
I'm currently using client_credentials for my token. I am successfully making GET browse/{series_type} calls and obtaining the "id" returned from each of those entries. 

What I then try to do is use those IDs to obtain Characters/Staff; first I tried using ``` GET anime/[ID]/characters``` but I get a 404. I realize that the format is ```GET {series}/{id}/characters```, but what do I need to put into {series} parameter since it's not the same as {series_type}?

I also tried following using ```GET: {series_type}/{id}``` under Routes/Basic doc by using ```GET anime/[ID]``` (ID obtained from the previous browse call) but this gives me an access_denied error.

Any advice will help.

Thanks!

**Comment by Kazakuri** [comment]
Can you give me an example of a specific call you're trying to make? It looks like I can call `GET anime/[ID]/characters` just fine.

![http://i.imgur.com/vNokvfn.png](http://i.imgur.com/vNokvfn.png)

**Comment by yydrvs** [comment]
D'oh, I somehow didn't pass in the token in my new call, sorry about that. ```anime/[ID]/characters``` indeed is working now, but trying to do ```anime/[ID]/staff``` or ```anime/[ID]/actors``` gives me an unavailable route. Have these two options been deprecated?

**Comment by Kazakuri** [comment]
I can't find anything that shows they were ever valid routes at all to be honest, it seems like a bit of misinformation to me.

I'll pester Josh about it in the morning, but yeah it seems like they're not there anymore and should be removed from the documentation at least.

**Comment by yydrvs** [comment]
Thanks for the quick response and clarification! It seems I can leverage the ```actor``` key/value from the ```anime/[ID]/characters``` response for my use case.

**Comment by Kazakuri** [comment]
Glad to hear it worked out. Feel free to open another issue if you have anymore questions or concerns!
