### ISSUE TITLE
Inconsequent capitalization of the token_type "Bearer"

### ISSUE THREAD

**Issue by Nehmulos** [joshstar/AniList-API-Docs#38]
```auth/access_token``` responds with ```token_type: "bearer"```, but the actual authentication header requires: ```Authorization: Bearer access_token```.
If you try sending it in lower case like: ```Authorization: bearer access_token``` 
you get ```{"status":401,"error":"unauthorized","error_message":"Access token is not valid"}```.

Affected document:
https://github.com/Josh-Star/AniList-API-Docs/blob/master/source/authentication.rst

I just googled "Oauth Bearer" and the example sends ```"token_type":"Bearer"```
https://tools.ietf.org/html/rfc6750#section-4

**Comment by alucard112** [comment]
+1

**Comment by joshstar** [comment]
This should be fixed in the new back end coming in a month of so.
