### ISSUE TITLE
Cloudflare Requires a User-Agent Header

### ISSUE THREAD

**Issue by ORYLY** [joshstar/AniList-API-Docs#46]
Cloudflare responds with 403 Forbidden if the request doesn't have a User-Agent header. This should be listed in the docs or Cloudflare should be configured not to be so anal.

**Comment by Josh-Star** [comment]
Yeah sorry about this, cloudflare is just enabled temporary again while we work some bandwidth issues out. I'll look into configuring cloudflare to make it easier to work with but it should be disabled soon enough anyway.
