### ISSUE TITLE
Date format inconsistency (future dates)

### ISSUE THREAD

**Issue by danejur** [joshstar/AniList-API-Docs#52]
According to the spec, dates are returned in a format similar to the following example:

"start_date": "1998-04-03T21:00:00+09:00"

However, there appears to be some anomalous behavior when fetching information about shows with no concrete start date (limited to a year, for example). For instance:

{
    "id": 20875,
    "title_romaji": "Sword Gai",
    "type": "TV",
    "image_url_med": "http://anilist.co/img/dir/anime/med/20875.jpg",
    "image_url_sml": "http://anilist.co/img/dir/anime/sml/20875.jpg",
    "start_date": "2016"
}

Would it be possible to allow start_date and end_date to return null if no concrete date is known, and instead put more vague date information into their own string fields?

**Comment by Josh-Star** [comment]
Yeah this is a good idea and I'll implement it soon. I'll have to do a little bit of work adding support of this to anichart so it might take a little while longer.

**Comment by joshstar** [comment]
Not sure how this took almost a year to get around to but start_date_fuzzy and end_date_fuzzy will be available once the new back end goes live in the next month or so.

Fuzzy date format: YYYYMMDD 
If a date is not known, 00 will be used instead, for example May 2016 would be 20160500, or just 2016 would be 20160000.

The current start and end dates will be considered deprecated, but still available for backwards compatibility.
