### ISSUE TITLE
"genres_exclude" param does not work.

### ISSUE THREAD

**Issue by EgorDm** [joshstar/AniList-API-Docs#53]
Hello,

I have been trying to use "genres_exclude" param in the url's but it doesn't seem too work.
Here are a few steps to reproduce:
Here is just a url to get popular results
https://anilist.co/api/browse/anime?access_token=MYTOKEN&sort=popularity-desc
The anime "Shingeki no Kyojin" is at the top and it has "Action, Drama, Fantasy, Super Power" genres assigned to it. But when i try to filter it out by adding some of these genres to the "genres_exclude" parameter "Shingeki no Kyojin" is still at the top.
Neither this: 
https://anilist.co/api/browse/anime?access_token=MYTOKEN&sort=popularity-desc&genres_exclude=Drama
or this: 
https://anilist.co/api/browse/anime?access_token=MYTOKEN&sort=popularity-desc&genres_exclude=Drama,Action
works.

Could that be that be some bug or I am using it wrong?

**Comment by Kazakuri** [comment]
Yeah, genres_exclude does not work without genres right now.

For example: this will not work
http://anilist.co/browse/anime?genres_exclude=Action&sort=popularity-desc
But this will
http://anilist.co/browse/anime?genres=Super%20Power&genres_exclude=Action&sort=popularity-desc

**Comment by EgorDm** [comment]
Aha, so genres_exclude only works when you also filter it for some genres. Are there any plans for changing it in the future or will it stay like this? I was trying to filter out some genres which are not really approperiate for many audiances.
But for now I will filter for the genres I want instead and exclude the unneeded ones.
Thanks for the help.

**Comment by Kazakuri** [comment]
As far as I know it's an unintended drawback, but Josh will have to confirm that.

**Comment by joshstar** [comment]
This is fixed in the new back end coming in the next month or so.
