### ISSUE TITLE
Request: Start/End Dates, Airing data in user lists

### ISSUE THREAD

**Issue by Birdulon** [joshstar/AniList-API-Docs#59]
Currently there does not appear to be a non-abusive way of gathering all the start/end dates for items. Airing data is less of an issue thanks to the browse API covering all shows of interest but it would still be nice to be able to get it from list requests.

**Comment by Josh-Star** [comment]
Yeah the small data models are just too restrictive at the moment, and other no customizability for additional fields like start/end date, something I do want to change. I'm super busy at the moment so I don't know when I'll be able to look into this, but even when I do I'm not sure its something we can much about with the current API setup. 

The API was kind of intentionally made restrictive with things like dates and full data models in an effort to stop people from creating super quick anichart clones, but I'm not sure that was the best idea in hindsight and I don't think the cloning issue is that big of a worry anymore.

Anyway I think this may be something we have to leave until APIv2, which won't be until after we open source, probably Q1 next year, sorry.

**Comment by Birdulon** [comment]
No worries, hope to see it next year!
