### ISSUE TITLE
App tab showing multipe apps?

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#64]
![image](https://cloud.githubusercontent.com/assets/5322473/12301745/f53c1884-ba21-11e5-9600-41ef8b030fe4.png)
it goes all the way down...

**Comment by Josh-Star** [comment]
Yeah I noticed this the other day too, but it was only with 2 copies so I didn't think much of it. I'll look into this, I guess its something to do with the multi-devicr support we added awhile ago.

To clear them if you revoke one it should remove them all at least

**Comment by ratan12** [comment]
But if I remove one and all will be removed wouldn't it cause issues with users trying to make API requests?

**Comment by Kazakuri** [comment]
As far as I know, the Approved Apps is only the refresh / access token linked to your account.

So revoking them will only give issues for users using your access token, which should only be you.

**Comment by ratan12** [comment]
wasn't "ANILIST_CLIENT_ID" also linked to it?

**Comment by Kazakuri** [comment]
You request the access token using the client id and client secret.
Deleting the application from Approved Apps shouldn't affect the client id and client secret, it should only delete the refresh token and access token for the currently logged on user.

**Comment by joshstar** [comment]
Closing this as this isn't really much of an issue we can fix. Each app in the list is an app for a different device or at least device session. In the future we'll look to associating a device id with each app approval to make the multiples make more sense.
