### ISSUE TITLE
Forum tags not working?

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#68]
Am I doing something wrong? 8 = music which should work without manga and anime id right?

![image](https://cloud.githubusercontent.com/assets/5322473/13057430/6b5c024a-d41c-11e5-8200-e75b8d507700.png)

**Comment by joshstar** [comment]
Oops sorry thats a mistake in the docs, the url param should be tags not tag, as you can request multiple like tags=9,8
