### ISSUE TITLE
Wrong date format in forums

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#69]
`last_reply:2016-02-09 20:10:09`
This is not a ISO format. I do not see the timezone.

**Comment by joshstar** [comment]
Sorry but at this point changing any date/time formats could easily break compatibility with other api clients so I think we'll just have to live with the inconsistency for now.

All times from AniList are in the JST timezone.
Date/times will definitely all be consistent in API v2, and we'll have a better way of dealing with API versioning for v2 too so if there are issues like this we'll be able to fix it before a major version update.

I'll #57 for the same reasons too.
