### ISSUE TITLE
Updating records are not being displayed right in the activity

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#72]
If an user update his/her records it does change on the website but it won't be displayed right in her/his activity.

**Comment by Nehmulos** [comment]
I have the same thing going on. It changes in the AnimeList, but there is no item generated in the Feed. Only status changes do generate feed activity (for example watching -> completed).

The site used to create a Feed update with every 'episodes-watched' change. Is it supposed to be like this now?

**Comment by ratan12** [comment]
This repository is only for AniList. 
If it occurs on MAL it is their fault and it won't be fixed because they ignore developers.

**Comment by joshstar** [comment]
This should be fixed now, sorry it took awhile.
