### ISSUE TITLE
Animelist does not return anime object

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#73]
User WcDonalds has an issue while loading the app.
After investigation I found out that his animelist does not return the anime object somewhere.
Everything else seems to be fine.

List: plan to watch
record_id: 8341745
updated_time: 2015-07-25T03:56:39+09:00
added_time: 2015-07-25T03:56:15+09:00

These are the details which I can see. The anime object equals null.

`{"added_time":"2015-07-25T03:56:15+09:00","chapters_read":0,"episodes_watched":0,"record_id":8341745,"list_status":"plan to watch","priorty":0,"reread":0,"rewatched":0,"score_raw":0,"updated_time":"2015-07-25T03:56:39+09:00","volumes_read":0}`

**Comment by joshstar** [comment]
Sorry about that, should be fixed now.

**Comment by ratan12** [comment]
I haven't confirmed it but I saw a similar case for "Tide" in the crash logs.

**Comment by ratan12** [comment]
While you are at it I saw more similar logs.
"KuroshitsujiFan", "Shiroryujin" and "LovelyPanda99"

If it is an issue at your end could you send them a message that there was an issue which involved their animelist caused issues with third party clients?

**Comment by Kazakuri** [comment]
Just to help out a bit:

- **Tide:** Looks fine to me.
- **KuroshitsujiFan:** `record_id: 1717410` and `record_id: 7906788`
- **Shiroryujin:** 18 null anime records that look like they were the result of some sort of failed batch add? Most of the records are only a couple of seconds apart.
- **LovelyPanda99:** `record_id: 10470955`

**Comment by ratan12** [comment]
Tide must have noticed it an deleted the record.
I can clearly see that he had the issue on MAR 26 2016 08:29:47 (UTC)
`Anime.getId()' on a null object reference`

**Comment by ratan12** [comment]
@joshstar Any update about this issue?
