### ISSUE TITLE
Alternatives for upcoming & recent?

### ISSUE THREAD

**Issue by ratan12** [joshstar/AniList-API-Docs#76]
Are there alternative browse endpoints for:
anime/browse/recent
anime/browse/upcoming

They are not anymore in the docs so I guess those are deprecated now?

**Comment by joshstar** [comment]
They are deprecated but should still work. 

You can use the new browse/anime with the optional params (like ?sort=id-desc will get you the same as recently added) as alternatives of the old endpoints but with a bit more control.

**Comment by ratan12** [comment]
For users who also had questions about the upcoming endpoint:
sort: id-desc
status: Not Yet Aired
**and**
sort: id-desc
status: Not Yet Published
