### ISSUE TITLE
"browse/anime" only return small animes

### ISSUE THREAD

**Issue by ymhtut** [joshstar/AniList-API-Docs#77]
Me and my friend are developing a mobile app using AniList API. 
At ["browse/anime"](http://anilist-api.readthedocs.io/en/latest/anime.html#browse), I can only fetch data with **Small Anime Models**. Is there anyway I can fetch data with **Anime Model**?

We show the Animes with a list in the app. As we can get only data with **Small Anime Model**, we have fetch data from ["anime/{id}"](http://anilist-api.readthedocs.io/en/latest/anime.html#basic) again in order to show users the detail of an Anime. We also have some issues with it.  We will be very glad if we can fetch data with **Anime Model**. Thanks in advanced.

Regard,
Ye

**Comment by joshstar** [comment]
Currently its not possible to return the full anime model in places such as browse, this will be fixed in APIv2 as we won't have small model variants for the most part. APIv2 will be out later this year, sorry I can't provide anything better at the current time.
