### ISSUE TITLE
Follow Endpoint Failing

### ISSUE THREAD

**Issue by ccubed** [joshstar/AniList-API-Docs#80]
Given the same Oauth Access Token.

The endpoint /user/ will work when authenticated against that access token.

The endpoint /user/follow will fail with a 401 Unauthorized stating that the Access Token is invalid.

I've verified that it's not just complaining about it being passed through the Headers because when passing it through the url params it returns Access Token Missing instead.

Example action: User TakeshiKO (ID: 6301) is authenticated via Oauth. We send his access token to the follow endpoint with the posted data being: id: 15281 in json. This is the id of User Kin.

**Comment by Kazakuri** [comment]
It shouldn't be failing at all.

```
POST http://anilist.co/api/user/follow?id=38626
Authorization: Bearer <token>
Content-Type: application/json

 -- response --
200 OK
Date:  Fri, 27 May 2016 14:59:28 GMT
Content-Type:  text/html; charset=UTF-8
Transfer-Encoding:  chunked
Connection:  keep-alive
X-Powered-By:  PHP/5.6.21-1~dotdeb+7.1
Cache-Control:  no-cache
Content-Encoding:  gzip

Followed
```

Are you properly passing the access token through the header?  

The format should be`Authorization: Bearer <token>`
Be careful about the the captialization of Bearer (see #38).

**Comment by ccubed** [comment]
I apologize. It was python passing the token as bytes instead of a string. So the endpoint is working.
