### ISSUE TITLE
Question about refreshing tokens.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#85]
When you receive an access token, you get an `expires` parameter like this:

`expires: 1414233512`

I'm assuming this is the UNIX Timestamp of when the token would expire.

My question is, do I have to refresh the token after it has expired, or is it possible to do it a few minutes or seconds earlier?

The reason I'm asking this is because (assuming this is a UNIX Timestamp) Anilist returns a Timestamp as an integer. Many systems are bound to return it as a double. For example, my system returns something like this:

1469335298.658988

So comparing to know when exactly I can refresh is a bit complicated.

**Comment by joshstar** [comment]
You can refresh the token at any time, if you do so before its expiration time, the previous token will automatically expire when you get the new token.

Yeah its a unix timestamp, I guess just cast away the fractional seconds as they aren't really relevant in this case?

**Comment by AndyIbanez** [comment]
Thanks. Yeah I will drop the decimals in my result before comparing it to the received `expires`.
