### ISSUE TITLE
Authorization APIs receive token type in lower caps; upper caps is required.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#87]
When you are requesting an access token and get a response, the token type should have the first letter capitalized. Otherwise, you cannot authenticate to the API.

In other words, it returns "bearer", when it should be "**B**earer". And yep, using the all lowercaps "bearer" does cause the API to give you a 401 error, but I'd say that's correct behavior.

```JSON
{
    access_token: "NR3M3vXgHK0kmluOcJVlRXvbGOg4yLhAVyf5If"
    token_type: "bearer"
    expires: 1414234981
    expires_in: 3600
}
```

This is no big deal, because I can write that part of the Authorization URL by hand, but ideally we should be able to grab the token type and build the rest of the header using it:

So Instead of (in my case) doing something like this:

`"Authorization" : "Bearer " + session.info.accessToken`

I can properly grab it from the JSON response doing something like this:

`Authorization" : session.info.tokenType + " " + session.info.accessToken`

Again this is no big deal, so assign the priority you wish, but it's still something that needs to be fixed. There's no shortage of workarounds like to use them in the meantime, thankfully.

**Comment by joshstar** [comment]
I've updated our oAuth 2 package for the backend update next month and this issue is fixed there.
