### ISSUE TITLE
Server Time.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#91]
There's some models that return a `created_at`. But there is no way to grab the user's time zone to properly adjust it. Are there plans to adjust the times automatically based on the user's timezone (By adding a timezone setting)?

In the meantime I have noticed that the server is one hour ahead of me, but I'd like to know it's timezone to properly format times to the user's local device.

EDIT: It's `created_at`, not `created_time`. Whoops.

**Comment by Kazakuri** [comment]
Server time is JST.

If anything is changed, things like `created_time` would be better returned as unix timestamps imo since they're timezone agnostic.

**Comment by AndyIbanez** [comment]
It would definitely be the best option to return the UNIX Timestamp. Most likely for v2? cc @joshstar

In the meantime I will do magic with the time I receive and the JST timezone. Arigatou Kazakuri.
