### ISSUE TITLE
Return the username in the activity model.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#92]
I noticed that the activity model does not return the username of the user that posted it, only their ID.

It should be present to easily be able to tell who posted what.

We do get an array of `SmallUser`s in each activity, and we can probably grab the first user to learn who posted what activity, but I'm not sure how reliable doing this will be.

**Comment by Kazakuri** [comment]
The `user_id` field can just be matched to an `id` in a small user model to find out the username.

As far as I know if there's multiple users in the `users` array it's because each user posted that activity (they all watched episode 4 of x) and AniList merged the activities.

**Comment by AndyIbanez** [comment]
That's a good workaround, wonder why I didn't think of it. Will do that for now, thanks.

**Comment by joshstar** [comment]
activity->users[0] will always be the user that created the activity, in the case of more users in the array (grouped activity) every user made the same activity post (excluding time). I would say the user_id value probably shouldn't be there as its not accurate for activity messages or grouped activity.

**Comment by joshstar** [comment]
Can this be closed?
