### ISSUE TITLE
Uncaught TypeError: $(...).unbind is not a function(…)

### ISSUE THREAD

**Issue by arkenthera** [joshstar/AniList-API-Docs#93]
Hey,

I'm trying to set up Anilist login process in our desktop application [Chiika](https://github.com/arkenthera/Chiika).
Its running on [Electron](https://github.com/electron/electron) so I thought it would be pretty easy to get the auth pin through launching the Anilist website when user wants to login. I'm creating a modal window then navigate to the redirect URL, then login page appears. 

![](http://i.imgur.com/ims40r8.png)

I know this is not a specific Anilist issue but why am I getting this error?
I also know that I could just launch the native Chrome from our app and load the redirect URL then make user copy paste the PIN but if we could login the user entirely from the app it would be much better. I planned that when user logged in inside our app , we will automatically copy the auth pin by executing javascript on the Anilist page so the user won't even copy paste the code. Can I work around this issue?

Electron is running Chrome **52.0.2743.82**

![](http://i.imgur.com/sQvyhdH.png)

my normal Chrome also is the same version (where this error doesn't appear)

![](http://i.imgur.com/1g9yqHV.png)

You can reproduce the issue by cloning [electron-quick-start](https://github.com/electron/electron-quick-start) and navigate to anilist.co

**Comment by joshstar** [comment]
I think the $(...).unbind error would be due to the lack of jquery? maybe? Would electron be doing something to overwrite $ or get in the way of jquery somehow?

The reason that code is there in the first place is due to chrome's login/password autofill not triggering angular's digest cycle, so we have to manually trigger it. Ideally I would just rather not use jquery but it becomes a pain to find dependencies that don't require it.

**Comment by arkenthera** [comment]
It is known that since Electron runs Node and Node injects bunch of stuff into DOM it causes problems with third party libraries like jQuery. To fix it we were already using ```window.$ = window.jQuery = require('....')``` I injected this to anilist login page before the app.js loads but to no avail. Also verified in the console that jQuery indeed works. I would like to solve this but I found a work around. By disabling node integration in Electron environment you can simulate real browser environment. I set ```nodeIntegration: false ``` and the problem went away. But since we disabled the node integration we'll have to find another way to extract the auth pin out of the DOM and send it to the main process.. somehow. 

![](http://i.imgur.com/ZcWzNe5.png) 

We can close this issue now.
