### ISSUE TITLE
What's an "Activity message"?

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#94]
I'm trying to figure what the "Activity Message" is. It's certainly different than an actual activity and a reply to an activity, but I can't figure out what it is.

I used this test account to "send" a message to my real account, and got this response back:

``` JSON
{
  "user_id": "Ibanez",
  "created_at": "2016-08-04 12:40:52",
  "id": 5694924,
  "status": null,
  "value": "Hi."
}
```

But I cannot find said message anywhere. My main account does not seem to have a message anywhere or even a notification. Similarly, I can't find anything in the test account I used to "send" that message.

**Comment by AndyIbanez** [comment]
Right, using the numerical user ID did cause the message to get posted in my activity feed.

I'm not sure if there's plans to change this API, but I'd suggest it does.

It would make sense to change it to:

```POST user/{user_id | username}/activity```

With the payload:

```text: (string) Message to post in the receiver's activity feed"```

It's currently a bit confusing as it is now. The parameter `messenger_id` is misleading, as it sounds like you have to put the sender's name there (instead of the receiver's, like it currently is).

It should also fail when it can't the message, like I just did. When I used my username, I received that JSON response and a 200 HTTP status code, so it was a little bit confusing.

**Comment by Kazakuri** [comment]
>The parameter `messenger_id` is misleading, as it sounds like you have to put the sender's name there (instead of the receiver's, like it currently is).

Well, to be fair `messenger_id` is documented as `messenger_id: (int) recipient user id`. I do agree it should be called something better like `recipient_id` though.

**Comment by joshstar** [comment]
In the new backend the entire request validation has been re-written so you'll get nice messages back if your request isn't valid, hopefully this won't be a breaking change as at the moment we just don't really return anything if theres an error so everyone has been going off status codes and ignoring the body.

Sending a non-numerical messenger_id value:
`{
  "error": {
    "status": 422,
    "messages": [
      "The messenger id must be a number."
    ]
  }
}`

Providing a messenger_id for a user that doesn't exist:
`
{
  "error": {
    "status": 422,
    "messages": [
      "The selected messenger id is invalid."
    ]
  }
}`

I do also agree messenger_id is not very clear so I've added `recipient_id` as an alternative too.

Generally post/put routes don't accept a string username and instead require the numerical id, I'm sure there are some inconsistencies there though, I'll look into to changing it anyway.


Considering we have these rules for almost every post/put route it would be good to add them to the docs once the new backend is live;
![Request rules](http://puu.sh/qpzwx/f3166a1139.png)

**Comment by AndyIbanez** [comment]
> hopefully this won't be a breaking change as at the moment

It should be fine if you still return the status code in the response header. I don't think it would break it for anyone then. Glad to see we will get actual body responses too.
