### ISSUE TITLE
Make Notifications Return More Relevant Data.

### ISSUE THREAD

**Issue by AndyIbanez** [joshstar/AniList-API-Docs#95]
Notifications for forum responses return information that can be used to get to that thread, but the same is not necessarily for all notification types.

Notifications for responses to activities do not give me anything that I can use to fetch relevant activity.

**Comment by Kazakuri** [comment]
`object_id` is the activity number.

Then you can get it with `https://anilist.co/api/user/activity/${object_id}`

**Comment by joshstar** [comment]
Currently notifications don't return the notification (object_type) type value, but in the new back-end they do. Apart from forum threads and users the only other thing notifications are made from is activity but I don't see too much point in adding that model with the notification as it doesn't really have a title or anything that can be used in the notification.

Here are the object_type values:
```
1: Reply to comment in forum thread (with user who replied and forum thread models)
2: User sent you an activity message (with user (message invoker) model and object_id => activity_id)
3: User replied to your activity (with user who replied model and object_id => activity_id)
4: User stated following you (with user model)
5: User @ mentioned you in activity (with user (@ invoker) model and object_id => activity_id)
6: User @ mentioned you in forum thread (with user (@ invoker), and forum thread models)
7: User commented in subscribed forum thread (with user and forum thread modes)
```

More recently we added support for direct comment chain linking in the forum, however notifications still haven't been updated to them so they just provide the thread at the moment.

**Comment by AndyIbanez** [comment]
That sounds great, is there an ETA for when will the new backend be deployed? Many of the tweaks sound great and they are going to help me write this better.

**Comment by joshstar** [comment]
Sometime this month, maybe a tiny bit later if the new server takes longer to get set up.

**Comment by AndyIbanez** [comment]
Can we make them return a unique ID? It would be handy if I wanted to implement a service that sends push notifications.

**Comment by joshstar** [comment]
The id of each notification should be in return data, and is unique for each notification. Unless you mean something else?

**Comment by AndyIbanez** [comment]
I'm redoing some calls right now and I have yet to get to notification again, but if this API hasn't changed, the API just returned an `object_id` that was a link to the activity it was related to, but there was never a unique ID for each notification.

**Comment by joshstar** [comment]
See id value:
![ss 2016-08-13 at 05 30 11](https://cloud.githubusercontent.com/assets/7507582/17644349/bfe4e434-617b-11e6-9364-da87961af2aa.png)

**Comment by AndyIbanez** [comment]
Alright, I got there and it definitely looks like we have a unique ID per notification now. Thanks.

On a different but related matter, it looks like the `user` property is always going to exist along with the `invoker_id` (that's what I gather from your explanation of the types above). The only one that will vary depending on the type is `thread`, correct?

Also, I have on my code a property called `comment`. I assume this one is no longer going to be used?

I really like the idea of notification types btw, it makes it much easier to work with them.

**Comment by danejur** [comment]
Hate to necro this, but I noticed recently the addition of notifications pertaining to show episodes airing and other good stuff. Would it be possible to update the list of object_types above with all of the current values? I don't mind peaking at what the site itself is getting back, but I don't think my user account has all of the different notification types represented.

**Comment by joshstar** [comment]
Sure, I should really add these to the docs but away from home at the moment so I'll try to do it when I get back after Christmas.

 ```
1: (No longer used, replaced with 8) Reply to comment in forum thread (with user who replied and forum thread models)
2: User sent you an activity message (with user (message invoker) model and object_id => activity_id)
3: User replied to your activity (with user who replied model and object_id => activity_id)
4: User stated following you (with user model)
5: User @ mentioned you in activity (with user (@ invoker) model and object_id => activity_id)
6: User @ mentioned you in forum thread (with user (@ invoker), and forum thread models)
7: User commented in subscribed forum thread (with user and forum thread modes)
8: Reply to comment in forum thread (with user who replied and forum comment model)
9: Watching anime aired (in the last 10 mins) (with anime model)
```

Currently the value for 9 is an array of strings while the rest are just strings: [ 'Episode ', ' of ', ' aired.' ]

**Comment by danejur** [comment]
Thanks a bunch! This looks good.
