### ISSUE TITLE
Returning genres in Browse

### ISSUE THREAD

**Issue by jefflau** [joshstar/AniList-API-Docs#96]
Hi there,

I'd like to be able to return either the normal model for the Anime by adding a param to set that to true. Or i'd like to be able to return genres to the small anime model. Are either of those two possible to implement? It would save me from making another request to your API as I can just filter them on the client if I have that extra information. 

Actually it'd just be nice to be able to set what extra keys you'd like that are already available in the large model as params to the request. But that sounds like a bit more work!

Thanks,

Jeff

**Comment by joshstar** [comment]
The first point is not possible at the moment (not until api v2) and I'm not sure what you mean in your second point; is it you want small anime models to include their genres or something else?

**Comment by jefflau** [comment]
Yeah exactly. So I'm returning all the anime in a season using /browse and I'd like to be able to see their genre. I'm returning all of them and I'd like to filter them on the client without having to make another API call

Sent from my iPhone

On Aug 6, 2016, at 3:48 AM, Josh Star <notifications@github.com<mailto:notifications@github.com>> wrote:


The first point is not possible at the moment (not until api v2) and I'm not sure what you mean in your second point; is it you want small anime models to include their genres or something else?

-

**Comment by jefflau** [comment]
Any update on this? If not I guess i'll have to rework my logic to just use the API for filtering genres (I can see you've got that setup). But i wanted to take advantage of caching all anime per season and just filtering on the front-end. Less work on the API too.

**Comment by joshstar** [comment]
I've added the genres array to the anime/manga small model, it should be live in the upcoming update later this month.

**Comment by jefflau** [comment]
Thanks a lot josh!

Sent from my iPhone

On Aug 9, 2016, at 5:46 AM, Josh Star <notifications@github.com<mailto:notifications@github.com>> wrote:


I've added the genres array to the anime/manga small model, it should be live in the upcoming update later this month.

-
