### ISSUE TITLE
API returning 500 Internal Server Error

### ISSUE THREAD

**Issue by vincent-paing** [joshstar/AniList-API-Docs#99]
Currently returning 500 Internal Server for every endpoint.

Here's the screenshot
http://i.imgur.com/F8TLLQJ.png

Tested on POSTMAN with dummy client

**Comment by ccubed** [comment]
I'm getting a 404 on the authorization endpoints. Hey, at least you got a 500!

**Comment by joshstar** [comment]
Sorry about that, should be fixed now.

**Comment by vincent-paing** [comment]
It is now returning 400 Bad Request for me even though I have passed grant_type as paramter

http://i.imgur.com/bTl7vSl.png
